Name:           ros-indigo-robot
Version:        1.1.4
Release:        0%{?dist}
Summary:        ROS robot package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-control-msgs
Requires:       ros-indigo-diagnostics
Requires:       ros-indigo-executive-smach
Requires:       ros-indigo-filters
Requires:       ros-indigo-geometry
Requires:       ros-indigo-robot-model
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-ros-base
Requires:       ros-indigo-xacro
BuildRequires:  ros-indigo-catkin

%description
A metapackage which extends ros_base and includes ROS libaries for any robot
hardware. It may not contain any GUI dependencies.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Aug 21 2015 Dirk Thomas <dthomas@osrfoundation.org> - 1.1.4-0
- Autogenerated by Bloom

