Name:           ros-indigo-ros-core
Version:        1.1.3
Release:        0%{?dist}
Summary:        ROS ros_core package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-catkin
Requires:       ros-indigo-cmake-modules
Requires:       ros-indigo-common-msgs
Requires:       ros-indigo-gencpp
Requires:       ros-indigo-genlisp
Requires:       ros-indigo-genmsg
Requires:       ros-indigo-genpy
Requires:       ros-indigo-message-generation
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-ros
Requires:       ros-indigo-ros-comm
Requires:       ros-indigo-ros-tutorials
Requires:       ros-indigo-rosbag-migration-rule
Requires:       ros-indigo-rosconsole-bridge
Requires:       ros-indigo-roscpp-core
Requires:       ros-indigo-rosgraph-msgs
Requires:       ros-indigo-roslisp
Requires:       ros-indigo-rospack
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-std-srvs
BuildRequires:  ros-indigo-catkin

%description
A metapackage to aggregate the packages required to use publish / subscribe,
services, launch files, and other core ROS concepts.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Dirk Thomas <dthomas@osrfoundation.org> - 1.1.3-0
- Autogenerated by Bloom

